image: node:10

stages:
  - test
  - build


client:
  stage: build
  before_script:
    - yarn install
  script:
    - cd client
    - yarn build:ssr
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/