image: node:12

stages:
  - test
  - build

client-test:
  stage: test
  before_script:
    - yarn install
  script:
    - cd client
    - yarn test:unit:ci
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/

client-build:
  stage: build
  before_script:
    - yarn install
  script:
    - cd client
    - yarn install --only=dev --no-shrinkwrap && yarn run build
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/