image: node:12

stages:
  - test
  - build

client:
  stage: test
  before_script:
    - yarn install
  script:
    - cd client
    - yarn test:unit:ci
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/

client:
  stage: build
  before_script:
    - yarn install
  script:
    - cd client
    - yarn build
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/