stages:
  - test
  - build

services:
  - postgres:9.6

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  ENVIRONMENT: test
  ALLOWED_HOSTS: '*'

clientTest:
  image: node:12
  stage: test
  script:
    - cd client
    - yarn install --prefer-offline --cache-folder .yarn
    - yarn test:unit:ci
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/

clientBuild:
  image: node:12
  stage: build
  script:
    - yarn install --prefer-offline --cache-folder .yarn
    - cd client
    - yarn install --only=dev --no-shrinkwrap && yarn run build
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - client/.yarn
      - client/node_modules/

apiTest:
  image: python:3.6
  stage: test
  script:
    - cd api/
    - apk update && \
      apk add --no-cache --virtual build-deps gcc python3-dev musl-dev && \
      apk add postgresql-dev
    - pip install --no-cache-dir -r requirements.txt
    - python manage.py test --verbosity=3